@echo off
echo Stopping old servers...
taskkill /F /IM node.exe 2>nul
timeout /t 2 /nobreak >nul
echo Starting Backend...
start cmd /k "cd C:\+Bethel\soccer\backend && node server.js"
timeout /t 3 /nobreak >nul
echo Starting Frontend...
start cmd /k "cd C:\+Bethel\soccer\frontend && npm start"
echo Done! Opening browser in 10 seconds...
timeout /t 10 /nobreak >nul
start http://localhost:3000
